/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KatakanaIndexImport } from './routes/katakana/index'
import { Route as HiraganaIndexImport } from './routes/hiragana/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KatakanaIndexRoute = KatakanaIndexImport.update({
  id: '/katakana/',
  path: '/katakana/',
  getParentRoute: () => rootRoute,
} as any)

const HiraganaIndexRoute = HiraganaIndexImport.update({
  id: '/hiragana/',
  path: '/hiragana/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hiragana/': {
      id: '/hiragana/'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof HiraganaIndexImport
      parentRoute: typeof rootRoute
    }
    '/katakana/': {
      id: '/katakana/'
      path: '/katakana'
      fullPath: '/katakana'
      preLoaderRoute: typeof KatakanaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hiragana': typeof HiraganaIndexRoute
  '/katakana': typeof KatakanaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hiragana': typeof HiraganaIndexRoute
  '/katakana': typeof KatakanaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hiragana/': typeof HiraganaIndexRoute
  '/katakana/': typeof KatakanaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hiragana' | '/katakana'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hiragana' | '/katakana'
  id: '__root__' | '/' | '/hiragana/' | '/katakana/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HiraganaIndexRoute: typeof HiraganaIndexRoute
  KatakanaIndexRoute: typeof KatakanaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HiraganaIndexRoute: HiraganaIndexRoute,
  KatakanaIndexRoute: KatakanaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hiragana/",
        "/katakana/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hiragana/": {
      "filePath": "hiragana/index.tsx"
    },
    "/katakana/": {
      "filePath": "katakana/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
