/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HiraganaImport } from './routes/hiragana'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HiraganaRoute = HiraganaImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hiragana': {
      id: '/hiragana'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof HiraganaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hiragana': typeof HiraganaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hiragana': typeof HiraganaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hiragana': typeof HiraganaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hiragana'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hiragana'
  id: '__root__' | '/' | '/hiragana'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HiraganaRoute: typeof HiraganaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HiraganaRoute: HiraganaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hiragana"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hiragana": {
      "filePath": "hiragana.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
